apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongodb   #for mongo db
        image: mongo:latest
        volumeMounts:
          - mountPath: /data/db
            name: mongo-vol
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: host-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - name: tcp 
      port: 27017 # default port we can change it.
      targetPort: 27017
  selector:
    app:  mongo-app