apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  my-test
  template:
    metadata:
      labels:
        app: my-test
    spec:
      containers:
      - name: my-test
        image: sudhanshugupta26/demo1:01
