apiVersion: v1
kind: Service
metadata:
  name: service-my-test-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app:  my-test
  type: LoadBalancer
